@startuml

title __UTILS's Class Diagram__\n

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.ChangeComponentOrientation {
        - theDialog : JDialog
        - theFrame : JFrame
        - theMenuBar : JMenuBar
        - thePanel : JPanel
        + ChangeComponentOrientation()
        + changeOrientationOfJDialogToLeft()
        + changeOrientationOfJDialogToRight()
        + changeOrientationOfJFrameToLeft()
        + changeOrientationOfJFrameToRight()
        + changeOrientationOfJMenubarToLeft()
        + changeOrientationOfJMenubarToRight()
        + changeOrientationOfJPanelToLeft()
        + changeOrientationOfJPanelToRight()
        + setTheDialog()
        + setTheFrame()
        + setTheMenuBar()
        + setThePanel()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.CustomKeyDispatcher {
        - capslockBtn : JButton
        + CustomKeyDispatcher()
        + dispatchKeyEvent()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.EmailValidator {
        {static} - EMAIL_PATTERN : String
        - matcher : Matcher
        - pattern : Pattern
        + EmailValidator()
        + validate()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.EncryptPassword {
        - digester : PooledStringDigester
        + EncryptPassword()
        + encryptPassword()
        + passwordIsMatch()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.GetLiveCurrencyRates {
        {static} - loggingEngine : LoggingEngine
        + GetLiveCurrencyRates()
        + getEURToTRYLiveCurrency()
        + getGBPToTRYLiveCurrency()
        + getGsonParser()
        + getUSDToTRYLiveCurrency()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.GetLiveWeather {
        {static} - loggingEngine : LoggingEngine
        + GetLiveWeather()
        + getCurrentLocationWeather()
        - getXMLParser()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.LoggingEngine {
        {static} - fileHandler : FileHandler
        {static} - formatter : LoggingFormatter
        {static} - instance : LoggingEngine
        {static} - logger : Logger
        {static} - theDirectory : Path
        {static} - theFilePath : Path
        + LoggingEngine()
        + changeLoggingLevel()
        {static} + getInstance()
        + setConsoleLogging()
        + setMessage()
        + setReady()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.LoggingFormatter {
        ~ dateTimeFormatter : DateTimeFormatter
        + format()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.PropertiesReader {
        {static} ~ FILE_PATH : String
        ~ inputStream : InputStream
        - hotelName : String
        {static} - logging : LoggingEngine
        - password : String
        - userName : String
        + PropertiesReader()
        + checkIsAdministrator()
        + getHotelName()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.ResourceControl {
        + newBundle()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.RoomNumberMaker {
        ~ counter : int
        ~ lastNum : int
        - roomNumbers : String[]
        - roomText : String
        + RoomNumberMaker()
        + getNotReservedRooms()
        + getRoomNumbers()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.SendEmailToUser {
        {static} - loggingEngine : LoggingEngine
        - message : Message
        - props : Properties
        + SendEmailToUser()
        + sendTheEmail()
        + setEmailBody()
        + setFrom()
        + setReadyForEmail()
    }
  }
  

  namespace com.coder.hms.utils {
    class com.coder.hms.utils.ShowReport {
        - LOGOPATH : String
        {static} - logging : LoggingEngine
        {static} - serialVersionUID : long
        + ShowReport()
        + loadReport()
        + showReport()
    }
  }
  

  com.coder.hms.utils.CustomKeyDispatcher .up.|> java.awt.KeyEventDispatcher
  com.coder.hms.utils.GetLiveCurrencyRates o-- com.coder.hms.ui.external.InformationFrame : infoFrame
  com.coder.hms.utils.LoggingFormatter -up-|> java.util.logging.Formatter
  com.coder.hms.utils.PropertiesReader o-- com.coder.hms.utils.EncryptPassword : passwordEncrypter
  com.coder.hms.utils.ResourceControl -up-|> java.util.ResourceBundle.Control
  com.coder.hms.utils.ShowReport -up-|> javax.swing.JFrame


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
