@startuml

title __DAO's Class Diagram__\n

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.CompanyDAO {
        {abstract} + deleteByName()
        {abstract} + getAllCompanies()
        {abstract} + getCompanyByName()
        {abstract} + saveCompany()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.CustomerDAO {
        {abstract} + deleteCustomerByReservationId()
        {abstract} + findCustomerByDocumentId()
        {abstract} + findCustomerByName()
        {abstract} + getAllCustomers()
        {abstract} + getSinlgeCustomerByReservId()
        {abstract} + save()
        {abstract} + update()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.HotelDAO {
        {abstract} + getHotel()
        {abstract} + saveHotel()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.HotelSystemStatusDAO {
        {abstract} + beginTransactionIfAllowed()
        {abstract} + getSystemStatus()
        {abstract} + updateSystemStatus()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.PaymentDAO {
        {abstract} + deletePayment()
        {abstract} + getAllPaymentsByRoomNumber()
        {abstract} + getEarlyPaymentByRoomNumber()
        {abstract} + getLastPayment()
        {abstract} + getPaymentById()
        {abstract} + getTotalCashDollarForOneDay()
        {abstract} + getTotalCashEuroPaymentsForOneDay()
        {abstract} + getTotalCashLiraPaymentsForOneDay()
        {abstract} + getTotalCashPoundPaymentsForOneDay()
        {abstract} + getTotalCreditDollarPaymentsForOneDay()
        {abstract} + getTotalCreditEuroPaymentsForOneDay()
        {abstract} + getTotalCreditLiraPaymentsForOneDay()
        {abstract} + getTotalCreditPoundPaymentsForOneDay()
        {abstract} + savePayment()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.PostingDAO {
        {abstract} + deletePosting()
        {abstract} + getAllPostingsByRoomNumber()
        {abstract} + getPostingById()
        {abstract} + getTotalCashDollarPostingsForOneDay()
        {abstract} + getTotalCashEuroPostingsForOneDay()
        {abstract} + getTotalCashLiraPostingsForOneDay()
        {abstract} + getTotalCashPoundPostingsForOneDay()
        {abstract} + getTotalCreditDollarPostingsForOneDay()
        {abstract} + getTotalCreditEuroPostingsForOneDay()
        {abstract} + getTotalCreditLiraPostingsForOneDay()
        {abstract} + getTotalCreditPoundPostingsForOneDay()
        {abstract} + savePosting()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.ReservationDAO {
        {abstract} + deleteReservation()
        {abstract} + findReservationByAgencyRefNo()
        {abstract} + findReservationById()
        {abstract} + findReservationByRefNo()
        {abstract} + findSingleReservByThisDate()
        {abstract} + getAllReservations()
        {abstract} + getLastReservation()
        {abstract} + getReservListByThisDate()
        {abstract} + getReservsAsWaitlist()
        {abstract} + saveReservation()
        {abstract} + updateReservation()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.RoomDAO {
        {abstract} + getAllRooms()
        {abstract} + getRoomByReservId()
        {abstract} + getRoomByRoomNumber()
        {abstract} + saveRoom()
        {abstract} + setAllRoomsAtClean()
        {abstract} + setAllRoomsAtDirty()
        {abstract} + setRoomCheckedOut()
        {abstract} + setSingleRoomAsCleanByRoomNumber()
        {abstract} + setSingleRoomAsDNDByRoomNumber()
        {abstract} + setSingleRoomAsDirtyByRoomNumber()
        {abstract} + updateRoom()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.TransactionManagement {
        {abstract} + beginTransactionIfAllowed()
    }
  }
  

  namespace com.coder.hms.dao {
    interface com.coder.hms.dao.UserDAO {
        {abstract} + changePasswordOfUser()
        {abstract} + getAllusers()
        {abstract} + getUserByName()
        {abstract} + saveUser()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
