@startuml

title __BEANS's Class Diagram__\n

  namespace com.coder.hms.beans {
    class com.coder.hms.beans.Blockade {
        - GroupName : String
        - Number : String
        - Status : String
        - Type : String
        {static} - serialVersionUID : long
        + Blockade()
        + Blockade()
        + getGroupName()
        + getNumber()
        + getStatus()
        + getType()
        + setGroupName()
        + setNumber()
        + setStatus()
        + setType()
        + toString()
    }
  }
  

  namespace com.coder.hms.beans {
    class com.coder.hms.beans.LocaleBean {
        {static} - instance : LocaleBean
        {static} - locale : Locale
        {static} - serialVersionUID : long
        + LocaleBean()
        {static} + getInstance()
        + getLocale()
        + setLocale()
    }
  }
  

  namespace com.coder.hms.beans {
    class com.coder.hms.beans.RoomCountRow {
        - currency : Object
        - personCount : Object
        - price : Object
        - roomNumber : Object
        - roomType : Object
        {static} - serialVersionUID : long
        + RoomCountRow()
        + RoomCountRow()
        + getCurrency()
        + getPersonCount()
        + getPrice()
        + getRoomNumber()
        + getRoomType()
        + setCurrency()
        + setPersonCount()
        + setPrice()
        + setRoomNumber()
        + setRoomType()
        + toString()
    }
  }
  

  namespace com.coder.hms.beans {
    class com.coder.hms.beans.RoomEarlyPaymentRow {
        - currency : Object
        - dateTime : Object
        - explanation : Object
        - price : Object
        {static} - serialVersionUID : long
        - title : Object
        - type : Object
        + RoomEarlyPaymentRow()
        + RoomEarlyPaymentRow()
        + getCurrency()
        + getDateTime()
        + getExplanation()
        + getPrice()
        + getTitle()
        + getType()
        + setCurrency()
        + setDateTime()
        + setExplanation()
        + setPrice()
        + setTitle()
        + setType()
        + toString()
    }
  }
  

  namespace com.coder.hms.beans {
    class com.coder.hms.beans.RoomInfoRow {
        - customerName : Object
        - customerSurname : Object
        - roomNumber : Object
        - roomType : Object
        + RoomInfoRow()
        + RoomInfoRow()
        + getCustomerName()
        + getCustomerSurname()
        + getRoomNumber()
        + getRoomType()
        + setCustomerName()
        + setCustomerSurname()
        + setRoomNumber()
        + setRoomType()
        + toString()
    }
  }
  

  namespace com.coder.hms.beans {
    class com.coder.hms.beans.SessionBean {
        {static} - Date : String
        {static} - SESSION_BEAN : SessionBean
        {static} - hotelName : String
        {static} - id : long
        {static} - name : String
        {static} - nickName : String
        {static} - password : String
        {static} - roomCount : int
        {static} - serialVersionUID : long
        {static} - surname : String
        {static} - tableRowCol : Object[]
        + getDate()
        + getHotelName()
        + getId()
        + getName()
        + getNickName()
        + getPassword()
        {static} + getRoomCount()
        {static} + getSESSION_BEAN()
        + getSurname()
        {static} + getTableRowCol()
        {static} + setDate()
        + setHotelName()
        + setId()
        + setName()
        + setNickName()
        + setPassword()
        {static} + setRoomCount()
        + setSurname()
        {static} + setTableRowCol()
    }
  }
  

  com.coder.hms.beans.Blockade .up.|> java.io.Serializable
  com.coder.hms.beans.LocaleBean .up.|> java.io.Serializable
  com.coder.hms.beans.RoomCountRow .up.|> java.io.Serializable
  com.coder.hms.beans.RoomEarlyPaymentRow .up.|> java.io.Serializable
  com.coder.hms.beans.SessionBean .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
